version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: redis-gui-postgres
    environment:
      POSTGRES_USER: redisgui
      POSTGRES_PASSWORD: redisgui_secret
      POSTGRES_DB: redisgui_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U redisgui"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-sample:
    image: redis:7-alpine
    container_name: redis-gui-sample
    command: redis-server --requirepass samplepassword --loglevel verbose
    ports:
      - "6379:6379"
    volumes:
      - redis_sample_data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: redis-gui-backend
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://redisgui:redisgui_secret@postgres:5432/redisgui_db
      JWT_ACCESS_SECRET: f0508aa7d4ce58703cc6ed3ae400a40b1bace075cde5685cf3ad7d2ee3e50b57
      JWT_REFRESH_SECRET: f65e189cf67c0cbf62603d9b0b4c44eb24e2781ba52f7b221963f47bc502c327
      ENCRYPTION_KEY: 9a08b1641705eba6b2bfb1295430c5bf37a3811d9eae238956c76b9c4039e3ec
      REDIS_BLACKLIST_URL: redis://redis-sample:6379
      REDIS_BLACKLIST_PASSWORD: samplepassword
      PORT: 4000
      FRONTEND_URL: http://localhost:3000
      OIDC_ENABLED: "true"
      OIDC_ISSUER_URL: "https://iam.khadg.com/realms/bitpin-tech-iam"
      OIDC_CLIENT_ID: "redisgui"
      OIDC_CLIENT_SECRET: "9a08b1641705eba6b2bfb1295430c5bf37a381"
      OIDC_REDIRECT_URI: http://localhost:4000/api/auth/oidc/callback
      CONFIG_FILE: /app/config.yaml
    volumes:
      - ./backend/config.yaml:/app/config.yaml:ro
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
      redis-sample:
        condition: service_started

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: redis-gui-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_sample_data:
